name: CommandSync
main: com.fuzzoland.CommandSyncClient.CSC
version: 2.3
author: YoFuzzy3

commands:
  sync:
    description: Synchronize commands across servers.
    
permissions:
  sync.use:
    description: Access to /sync.
    default: op